# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jonas Myhres blogg
email: jonas.n.myhre@uit.no
description: > # this means to ignore newlines until "baseurl:"
  I am doing research in machine learning. I am currently a visiting postdoc
  at the university of Minnesota.
#baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  jonasnm

# Build settings
markdown: redcarpet
